version: "2"
services:
  backend:
    container_name: bootstrap-a-simple-application-backend
    build:
      context: backend
    image: bootstrap-a-simple-application-backend:latest
    ports:
      - "8081:8081"
    restart: always
  frontend:
    container_name: bootstrap-a-simple-application-frontend
    build:
      context: frontend
    image: bootstrap-a-simple-application-frontend:latest
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - backend