server:
  port: 8081

spring:
  application:
    name: Building a Web Application with Spring Boot and Angular
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: bootstrap-a-simple-application
  liquibase:
    enabled: false
