server:
  port: 8081

spring:
  application:
    name: Building a Web Application with Spring Boot and Angular

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:;NON_KEYWORDS=USER
    username: sa
    password:
