server:
  port: 8081

spring:
  application:
    name: Building a Web Application with Spring Boot and Angular
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2/bootstrap-a-simple-application/h2;NON_KEYWORDS=USER
    username: sa
    password:
  h2:
    console:
      enabled: true # http://localhost:8081/h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # https://stackoverflow.com/questions/37903105/how-to-configure-spring-boot-to-use-file-based-h2-database
  liquibase:
    enabled: false
