server:
  port: 8081

spring:
  application:
    name: Spring Boot Tutorial – Bootstrap a Simple Application

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

